version: "3.8"
services:
  app:
    image: 577638354424.dkr.ecr.ap-south-1.amazonaws.com/staging/igm-protocol-server-engine:latest
    container_name: ${SERVICE_NAME}
    ports:
      - "${PORT}:${PORT}"
    restart: always
