calls:
  - config: "search"
    mode: "ASYNC"
    callback:
      config: "on_search"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "select_loan"
    mode: "SYNC"
    callback:
      config: "on_select_loan"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "select_approval"
    mode: "ASYNC"
    callback:
      config: "on_select_approval"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "select_after_amount_adjust"
    mode: "SYNC"
    callback:
      config: "on_select_after_amount_adjust"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "init_kyc"
    mode: "ASYNC"
    callback:
      config: "on_init_kyc"
      endpoint: "mapper/ondc"
      mode: "ASYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "init_personal_loan"
    mode: "SYNC"
    callback:
      config: "on_init_personal_loan"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "init_with_account_details"
    mode: "SYNC"
    callback:
      config: "on_init_with_account_details"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "confirm"
    mode: "SYNC"
    callback:
      config: "on_confirm"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "status"
    mode: "SYNC"
    callback:
      config: "on_status"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"
  - config: "update"
    mode: "SYNC"
    callback:
      config: "on_update"
      endpoint: "mapper/ondc"
      mode: "SYNC"
      unsolicitedEndpoint: "mapper/unsolicited"

  # - config: "on_search"
  #   endpoint: "mapper/ondc"
  #   mode: "ASYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_select_loan"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_select_approval"
  #   endpoint: "mapper/ondc"
  #   mode: "ASYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_select_after_amount_adjust"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_init_kyc"
  #   endpoint: "mapper/ondc"
  #   mode: "ASYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_init_personal_loan"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_init_with_account_details"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_confirm"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_status"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
  # - config: "on_update"
  #   endpoint: "mapper/ondc"
  #   mode: "SYNC"
  #   unsolicitedEndpoint: "mapper/unsolicited"
