protocol:
  search:
    $ref: "./common.yaml"


  on_search:
    $ref: "./common.yaml"


  select:
    $ref: "./common.yaml"

  
  on_select:
    $ref: "./common.yaml"


  init:
    $ref: "./common.yaml"

 
  on_init:
    $ref: "./common.yaml"

  confirm:
    $ref: "./common.yaml"

  on_confirm:
    $ref: "./common.yaml"


  update:
    $ref: "./common.yaml"


  on_update:
    $ref: "./common.yaml"

  status:
    $ref: "./common.yaml"

  on_status:
    $ref: "./common.yaml"

        
