BAP:
  $ref: ./configs/BAP/index.yaml
BPP:
  $ref: ./configs/BPP/index_loan.yaml
schema:
  $ref: ./configs/schema/FIS/index.yaml
attributes:
  personal-loan-flow-1:
    $ref: ./configs/attributes/personal-loan-flow-1/index.yaml
version: "1.0.0"

